application: Modeify
name: Modeify
domain: modeify.co

entries:
  - client/planner-app/index.js:build/planner-app/build.js
  - client/planner-app/style.css:build/planner-app/build.css
  - client/manager-app/index.js:build/manager-app/build.js
  - client/manager-app/style.css:build/manager-app/build.css

announcements:

organization:
  name: Conveyal
  url: http://conveyal.com

# Support Email Address
email:
  name: Trevor Gerhardt
  address: support@conveyal.com

# Geocoding
geocode:
  center: -77.105933,38.880148
  zoom: 13
  start_location:
    address: 4301 13th St NW Washington, DC 20011
    lat: 38.943037
    lng: -77.029199
  end_location:
    address: 2100 Wilson Blvd, Arlington, VA
    lat: 38.891254
    lng: -77.085016
  boundary_rect:
    min_lat: 38.5
    min_lon: -77.5
    max_lat: 39.5
    max_lon: -76.5

# Default application values
api_url: /api
base_url: http://localhost:5000

google_site_verification:

mapbox_access_token:
mapbox_base_style:
mapbox_label_style:
mapbox_base_style_manager:

mapzen:
  search:
    api_key:

r5:
  url: http://mock-host.com
s3_bucket: ''
segmentio_key: ''
static_url: /assets

lock:
  theme:
    logo: 'http://lorempixel.com/400/200/'
    primaryColor: '#fff'

About: >
  ## About

Terms: >
  ## Terms
